 #check roboshop user id exists or not ! if not create user id roboshop 
- name: create user
  hosts: localhost
  tasks:
  - name: check user roboshop exists or not
    ansible.builtin.command: id roboshop
    register: output # output is variable
     # when you want to run linux commands directly i.e in the case ansible module not available
     # until here,if we execute the command : it shows ERROR and exit without running the command in execution. 
     # when the user does not exists, ansible treating this failure and comeout by default
     # so we give (ignore_errors= true) ,this means it runs the command and ignores the ERROR! without exit in execution.
    ignore_errors: true
  - name: print command output # we are printing output variable to test
    ansible.builtin.debug:
      msg: "output is : {{output}}" 
  - name: print exit status
    # in json validation, the ERROR status shows exit status as rc:1 --false,exits. if exit status rc:0 --true notexit,runs.
    ansible.builtin.debug:
      msg: "{{output.rc}}" # output.rc means (output-->rc) ie inside output in exectution there is rc=1, we need it to print
    #until here, in the execution: shows msg : "1" in green=success
  #now we create roboshop as we got confirmation that user doesnot exist 
  - name: create user roboshop
    become: yes #to give sudo/root access to create user, this is only for this task 
    ansible.builtin.user:
      name: roboshop
    when: output.rc !=0
  
  