 #check roboshop user id exists or not ! if not create user id roboshop 
- name: create user
  hosts: localhost
  tasks:
  - name: check user roboshop exists or not
    ansible.builtin.command: id roboshop
    register: output # output is variable
     # until here,if we execute the command shows: ERROR and exited without running the command. 
     # so we give ignore_errors= true , this means it runs the execution without exit and it ignores the ERROR!
    ignore_errors: true
  - name: print command output # we are printing output variable to test
    ansible.builtin.debug:
      msg: "output is : {{output}}" 
  - name: print exit status
    # in json validation, the ERROR status shows exit status as rc:1 --false exits. if exit status rc:0 --true notexit n runs.
    ansible.builtin.debug:
      msg: "{{output.rc}}" # variable.rc  
  