- name: loops example
  hosts: localhost
  # you no need to give username and password through command line
  tasks:
  - name: Print the Names
    ansible.builtin.debug:
      msg: "Hello {{item}}" #item is the special variable in loop
    loop:
    - harika
    - anusha
    - apple