- name: install packages
  host: localhost
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.yum:
       name: "{{item}}"
       state: installed
      loop:
      - postmap
      - cyrus